
[info.basic]
firstname = "Keaton"
lastname = "Guderian"

[info.contact]
email = "keagud@protonmail.com"
phone = "(206)-321-2181"

[info.links]
github = "https://github.com/keagud"
website = "https://implicit.computer"

[education.overall]
school = "University of Washington, Seattle"
gpa = 3.88
year_start = 2016
year_end = 2020
achievements = [
  "graduated Cum Laude",
  "Made the Dean's List for every term that met the credit requirement (all but 2)"
]


[[education.degrees]]
name = "Bachelor of Arts, Linguistics"
relevent_courses = ""



